name: mxnet-tutorial-gpu
home: https://github.com/lsheiba/mxnet-tutorial-gpu.git
version: 1.0.0
description: Tensorflow Jupyter Notebook
sources:
  - https://github.com/lsheiba/mxnet-tutorial-gpu.git
maintainers:
  - name: Leonard Sheiba
keywords:
  - keubernetes
  - mxnet
  - jupiter
  - nvidia-gpu
icon: https://github.com/dmlc/web-data/blob/master/mxnet/image/mxnet-icon.png
